# Generated by Django 5.1.1 on 2024-09-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porcinos',
            options={},
        ),
    ]
