# Generated by Django 5.1.1 on 2024-09-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_alter_porcinos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porcinos',
            options={'managed': False},
        ),
    ]
